---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = F
)
```

Psychotherapy feedback on the counseling center assessment of psychological symptoms (CCAPS): Effects on outcome and client moderators of effectiveness  

Rebecca Janis dissertation for psychology PhD at Pennsylvania State University. Defended on June 11, 2020.  

While psychotherapy is largely effective, some clients do not improve and even get worse during treatment. Psychotherapy routine outcome monitoring and progress feedback have been shown to improve outcomes and reduce rates of worsening during treatment. The present study evaluates the effectiveness of a psychotherapy feedback system built for the Counseling Center Assessment of Psychological Symptoms (CCAPS), a routine outcome monitoring instrument designed for use in college counseling centers. Data collected before and after the implementation of the CCAPS feedback system showed that outcomes, defined as reliable worsening during treatment, pre to post treatment change, and rate of symptom change, were not improved after the addition of the feedback system. While the impact of feedback varied somewhat by counseling center, this variance was small. Further, the impact of feedback did not vary meaningfully by any client moderators tested. Implications and directions for future psychotherapy feedback research, as well as practice-oriented research, are discussed.  
